
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include_dir_merge_list automations
script: !include scripts.yaml
scene: !include_dir_merge_list scenes/

calendar:
  - platform: caldav
    url: http://192.168.1.177:8081/remote.php/dav/calendars/andy/personal/
    username: andy
    password: kRofd-9GaEj-8Cgqj-Sfk2L-xD3SG
# sensor:
#   - platform: glances
#     host: brain
#     port: 61208
#     name: brain_stats
#     resources:
#       - cpu_percent
#       - memory_used
#       - memory_free
#       - disk_use_percent
#       - docker_active
#       - docker_cpu_percent
#       - docker_memory_percent
sensor:
  - platform: rest
    name: Brain CPU Usage
    resource: http://cy:61208/glances/api/3/cpu
    value_template: "{{ value_json.percent }}"
    scan_interval: 30
    
  - platform: rest
    name: Brain RAM Usage
    resource: http://cy:61208/glances/api/3/mem
    value_template: "{{ value_json.percent }}"
    scan_interval: 30

  - platform: rest
    name: Brain Disk Usage
    resource: http://cy:61208/glances/api/3/fs
    value_template: "{{ value_json[0].percent }}"
    scan_interval: 60
  - platform: teamtracker
    team_id: 66  # Iowa State Cyclones (ESPN ID)
    #league: NCAAF
    name: iowa_state_score
    
lovelace:
  dashboards:
    buzzgate-monitor:
      mode: yaml
      title: Buzzgate Monitor
      icon: mdi:server
      filename: dashboards/buzzgate-monitor.yaml
      show_in_sidebar: true
input_datetime:
  evening_scene_time:
    name: Evening Scene Time
    has_time: true
    has_date: false
timer:
  bedroom_motion_hold:
    name: Bedroom Motion Hold
    duration: "00:00:00"
  




