
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include_dir_merge_list config/automations
script: !include config/scripts.yaml
scene: !include_dir_merge_list config/scenes
sensor: !include_dir_merge_list config/sensors

calendar:
  - platform: caldav
    url: http://192.168.1.177:8081/remote.php/dav/calendars/andy/personal/
    username: andy
    password: REDACTED_NC_CALDAV_PW

lovelace:
  dashboards:
    buzzgate-monitor:
      mode: yaml
      title: Buzzgate Monitor
      icon: mdi:server
      filename: dashboards/buzzgate-monitor.yaml
      show_in_sidebar: true
input_datetime:
  evening_scene_time:
    name: Evening Scene Time
    has_time: true
    has_date: false
timer:
  bedroom_motion_hold:
    name: Bedroom Motion Hold
    duration: "00:00:00"


shell_command:
  play_alert: 'aplay /home/pi/alert.wav'  




