
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include_dir_merge_list automations
script: !include scripts.yaml
scene: !include_dir_merge_list scenes/

calendar:
  - platform: caldav
    url: http://192.168.1.177:8081/remote.php/dav/calendars/andy/personal/
    username: andy
    password: kRofd-9GaEj-8Cgqj-Sfk2L-xD3SG



