
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include_dir_merge_list automations
script: !include_dir_merge_list scripts
scene: !include_dir_merge_list scenes
sensor: !include_dir_merge_list sensors
cover: !include_dir_merge_list covers

conversation:
# assist:
# assist_pipeline: 
#   pipelines: 
#     - name: "Default Pipeline" 
#       conversation_engine: conversation.default 
#       language: "en"

# todo:
#   - platform: local
#     name: Groceries
input_text:
  mealie_recipe_id:
    name: Mealie Recipe ID

#calendar:
 # - platform: caldav
  #  url: http://192.168.1.177:8081/remote.php/dav/calendars/andy/personal/
   # username: andy
    #password: kRofd-9GaEj-8Cgqj-Sfk2L-xD3SG

rest_command:
  mealie_get_recipe:
    url: "http://cy:9000/api/recipes/{{ recipe_id }}"
    method: GET
    headers:
      Authorization: "Bearer YOURTOKEN"
    verify_ssl: false


  directus_create_task:
    url: "http://directus:8055/items/tasks"
    method: POST
    headers:
      Authorization: "Bearer v6j7JPGHHFmKUyYGQgUViYCXwb4ItAXH"
      Content-Type: "application/json"
    payload: >
      {
        "title": "{{ title }}",
        "status": "pending",
        "priority": "",
        "list": "{{ list_id }}",
        "assigned_to": "",
        "source": "ha",
        "external_id": "{{ external_id }}"
      }
  
    
lovelace:
  dashboards:
    buzzgate-monitor:
      mode: yaml
      title: Buzzgate Monitor
      icon: mdi:server
      filename: dashboards/buzzgate-monitor.yaml
      show_in_sidebar: true
input_datetime:
  evening_scene_time:
    name: Evening Scene Time
    has_time: true
    has_date: false
timer:
  bedroom_motion_hold:
    name: Bedroom Motion Hold
    duration: "00:02:00"
  tyler_motion_hold:
    name:  Tyler Motion Hold
    duration: "00:02:00"


shell_command:
  play_alert: 'aplay /home/pi/alert.wav'  




