Created this in the covers/groups.yaml

# cover:
#   - platform: group
#     name: Living Room Curtains
#     entities:
#       - cover.living_room_curtain_north
#       - cover.living_room_curtain_south_fixed
