- id: buzzgate_morning_bedroom_curtains
  alias: Buzzgate Morning Beedroom Curtains
  trigger:
    - platform: time
      at: "08:30:00"
  action:
    - service: cover.open_cover
      target:
        entity_id: 
          - cover.kia_s_curtain
          - cover.0x583bc2fffe034cc0 # Tyler's curtain
  mode: single
