- id: call_mom
  alias: Call Mom
  description: "Triggered by Kiasbutton MQTT action"

  trigger:
    #- platform: mqtt
    #  topic: zigbee2mqtt/kiasButtons
    #  value_template: "{{ value_json.action }}"
    #  value: "1_single"
    - platform: state
      entity_id: sensor.kiasbutton_action
      to: "1_single"  

  condition: []

  action:
  - service: mqtt.publish
    data:
      topic: zigbee2mqtt/alert_lights/set
      payload: >
        {"state":"ON","brightness":200}

  - delay: "00:00:02"

  - service: mqtt.publish
    data:
      topic: zigbee2mqtt/alert_lights/set
      payload: >
        {"state":"OFF"}

  - service: shell_command.play_alert

  - service: mqtt.publish
    data:
      topic: buzzgate/alert
      payload: "bathroom_call"


  mode: restart
