- id: buzzgate_evening_scene_on
  alias: Buzzgate Evening Scene On
  trigger:
    - platform: time
      at: "16:45:00"
  action:
    - service: scene.turn_on
      target:
        entity_id: scene.buzzgate_evening_on
    - service: cover.close_cover
      target:
        entity_id: 
          - cover.living_room_curtains
          - cover.deck_door_curtains
          - cover.kia_s_curtain
  mode: single
