- id: kia_button4_curtains_test
  alias: Kia Button4 Curtains Test
  trigger:
    - platform: state
      entity_id: sensor.kiasbutton_action
      to: "4_single"
  action:
    - service: cover.close_cover
      target:
        entity_id: cover.living_room_curtains
    - service: logbook.log
    data:
      name: "Curtain Toggle"
      message: "Button4 pressed"
    - service: cover.close_cover
      target:
        entity_id: cover.living_room_curtains
