alias: Kia Room - Night Motion
trigger:
  - platform: state
    entity_id: binary_sensor.kia_s_room_motion_occupancy
    to: "on"
condition:
  - condition: time
    after: "20:00:00"
action:
  - service: light.turn_on
    target:
      entity_id: light.kia_s_bedroom_rgb
    data:
      brightness_pct: 50
      rgb_color: [128, 0, 255]   # purple
mode: restart
