automation:
  - id: buzzgate_sundown
    alias: Buzzgate Sundown
    description: "Close living room curtains at sunset"
    trigger:
      - platform: sun
        event: sunset - 20 #20 minutes before sunset.
    action:
      - service: scene.turn_on
        target:
          entity_id: scene.buzzgate_sundown
    mode: single
