- platform: rest
  name: Mealie Recipe
  resource_template: "http://192.168.1.177:8085/api/recipes/{{ states('input_text.mealie_recipe_id') }}"
  headers:
    Authorization: "Bearer REDACTED_MEALIE_JWT"
  value_template: "{{ value_json.name }}"
  json_attributes:
    - ingredients

