- platform: rest
  name: Mealie Recipe
  resource: "http://192.168.1.177:9000/api/recipes/1"
  headers:
    Authorization: "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJsb25nX3Rva2VuIjp0cnVlLCJpZCI6IjUxZGVlZTQyLTM0ZTUtNDMyNC05MjRjLWQ0YTc2OTBjYTliOCIsIm5hbWUiOiJIQSBJbnRlZ3JhdGlvbiIsImludGVncmF0aW9uX2lkIjoiZ2VuZXJpYyIsImV4cCI6MTkyNjk3ODkzN30.WxC_yOj0M9MF0f6wGP7hGF3KG2d5Jp4BFQWPk2OhNQU"
  scan_interval: 3600
  value_template: "{{ value_json.name }}"
  json_attributes:
    - ingredients
