- platform: rest
  name: Mealie Recipe
  resource_template: "http://192.168.1.177:8085/api/recipes/{{ states('input_text.mealie_recipe_id') }}"
  headers:
    Authorization: "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJsb25nX3Rva2VuIjp0cnVlLCJpZCI6Ijk5NzI1ZGQxLWQxNDMtNDBmMy1hYmRhLTYxMTllNWJlODBhZCIsIm5hbWUiOiJIb21lIEFzc2lzdGFudCIsImludGVncmF0aW9uX2lkIjoiZ2VuZXJpYyIsImV4cCI6MTkyNjk4MzQ3Mn0.jYCbN2BXN3KsQRnQVVOlkzXYmKzpJsvnpUgpCVBo7jM"
  value_template: "{{ value_json.name }}"
  json_attributes:
    - ingredients

