homeassistant:
  enabled: true
  discovery_topic: homeassistant
  status_topic: homeassistant/status
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://cy-mosquitto-z2m:1883
serial:
  adapter: ezsp
  port: /dev/ttyUSB0 #this is pointing to the port where the coordinator (below) lives
  # port: /dev/serial/by-id/usb-SMLIGHT_SMLIGHT_SLZB-07_eccaf5a21f72ef11b8da3b848fcc3fa0-if00-port0
# serial:
#   adapter: zstack
#   port: tcp://192.168.1.171:6638
#   socket-timeout: 60
frontend:
  enabled: true
  port: 4242
advanced:
  log_level: info
  pan_id: 6754
device_options:
  retain: false
onboarding: false
channel: 15
version: 4
groups:
  '1':
    friendly_name: kitchen
  '2':
    friendly_name: hallway
  '3':
    friendly_name: master-bedroom
  '4':
    friendly_name: entryway
  '5':
    friendly_name: livingroom-ceiling
  '6':
    friendly_name: alert_lights
