
homeassistant:
  enabled: true
  discovery_topic: homeassistant
  status_topic: homeassistant/status
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://172.20.0.2:1883
serial:
  adapter: zstack
  port: tcp://192.168.1.171:6638
  socket_timeout: 60
frontend:
  enabled: true
  port: 4242
advanced:
  log_level: info
  pan_id: 6754
device_options:
  retain: false
onboarding: false
channel: 11
version: 4
devices: {}



