
homeassistant:
  enabled: true
  discovery_topic: homeassistant
  status_topic: homeassistant/status
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://172.20.0.2:1883
serial:
  adapter: zstack
  port: tcp://192.168.1.171:6638
frontend:
  enabled: true
  port: 8080
advanced:
  log_level: info
  network_key:
    - 1
    - 3
    - 5
    - 7
    - 9
    - 11
    - 13
    - 15
    - 0
    - 2
    - 4
    - 6
    - 8
    - 10
    - 12
    - 13
  pan_id: 6754
device_options:
  retain: false
onboarding: false
devices:
  '0xb0ce1814002148f6':
    friendly_name: kitchen-center
  '0xb0ce1814001d4cb7':
    friendly_name: master4
  '0xb0ce181400214913':
    friendly_name: kitcher-sw
  '0xb0ce181400214c18':
    friendly_name: kitchen-se
  '0xb0ce1814001d44a0':
    friendly_name: master2
  '0xb0ce181400189493':
    friendly_name: entryway-small
  '0xb0ce1814001d488c':
    friendly_name: master3
  '0xb0ce181400214ac5':
    friendly_name: kitchen-ne
  '0xb0ce1814001afa2d':
    friendly_name: hall-n
  '0xb0ce1814001d58ee':
    friendly_name: master1
  '0xb0ce181400214aaa':
    friendly_name: kitchen-nw
  '0xb0ce181400214c05':
    friendly_name: Entryway-flood
  '0xb0ce1814001afd37':
    friendly_name: dining-room
  '0xb0ce1814001af7a6':
    friendly_name: hall-s
version: 4


