homeassistant:
  enabled: true
  discovery_topic: homeassistant
  status_topic: homeassistant/status
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://cy-mosquitto-z2m:1883
serial:
  adapter: zstack
  port: tcp://192.168.1.171:6638
  socket-timeout: 60
frontend:
  enabled: true
  port: 4242
advanced:
  log_level: info
  pan_id: 6754
device_options:
  retain: false
onboarding: false
channel: 11
version: 4
devices:
  '0xb0ce1814001afd37':
    friendly_name: dining-room
  '0xb0ce181400214c18':
    friendly_name: kitchen-se
  '0xb0ce181400214913':
    friendly_name: kitcher-sw
  '0xb0ce181400214ac5':
    friendly_name: kitchen-ne
  '0xb0ce181400214aaa':
    friendly_name: kitchen-nw
  '0xb0ce1814002148f6':
    friendly_name: kitchen-center
  '0xb0ce181400214c05':
    friendly_name: Entryway-flood
  '0xb0ce1814001afa2d':
    friendly_name: hall-n
  '0xb0ce1814001af7a6':
    friendly_name: hall-s
  '0xb0ce1814001d44a0':
    friendly_name: master2
  '0xb0ce1814001d4cb7':
    friendly_name: master4
  '0xb0ce1814001d488c':
    friendly_name: master3
  '0xb0ce1814001d58ee':
    friendly_name: master1
  '0xb0ce181400189493':
    friendly_name: entryway-small
  '0xb40e060fffe07222':
    friendly_name: entryway-closet
  '0xb0ce1814001b04ee':
    friendly_name: lr-cieling-2
  '0xb0ce1814001af4d4':
    friendly_name: lr-cieling-1
  '0xb0ce18140005f7e5':
    friendly_name: lr-cieling-4
  '0xb0ce18140005e9d8':
    friendly_name: lr-cieling-3
  '0xb0ce18140005faaf':
    friendly_name: lr-cieling-5
  '0xb40e060fffe07255':
    friendly_name: bedroom_motion
  '0xb0ce18140005d14f':
    friendly_name: front-stoop
groups:
  '1':
    friendly_name: kitchen
  '2':
    friendly_name: hallway
  '3':
    friendly_name: master-bedroom
  '4':
    friendly_name: entryway
  '5':
    friendly_name: livingroom-ceiling
