
homeassistant:
  enabled: true
  discovery_topic: homeassistant
  status_topic: homeassistant/status
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://172.20.0.2:1883
serial:
  adapter: zstack
  port: tcp://192.168.1.171:6638
frontend:
  enabled: true
  port: 4242
advanced:
  log_level: info
  network_key:
    - 1
    - 3
    - 5
    - 7
    - 9
    - 11
    - 13
    - 15
    - 0
    - 2
    - 4
    - 6
    - 8
    - 10
    - 12
    - 13
  pan_id: 6754
device_options:
  retain: false
onboarding: false
channel: 11
version: 4
devices: {}



