[Interface]
Address = 10.13.13.3
PrivateKey = REDACTED_WG_TABLET_PRIVKEY
ListenPort = 51820
DNS = 192.168.1.177

[Peer]
PublicKey = 7zsDDu+EOpl5PwWz6x56/nXXc/t9fcwizAc20dLtpGQ=
PresharedKey = REDACTED_WG_TABLET_PSK
Endpoint = 208.126.129.241:51820
AllowedIPs = 0.0.0.0/0, ::/0
