- platform: group
  name: Living Room Curtains
  entities:
    - cover.lr_curtain_north
    - cover.lr_curtain_south

- platform: group
  name: All Curtains
  entities:
    - cover.lr_curtain_north
    - cover.lr_curtain_south
    - cover.master_curtain
    - cover.tyler_curtain
    - cover.kia_curtain
    - cover.dining_curtain

