- platform: group
  name: Kitchen Under Cabinet
  entities:
    - light.kitchen_uc_1
    - light.kitchen_uc_2
    - light.kitchen_uc_3
    - light.kitchen_uc_4
    - light.kitchen_uc_5

- platform: group
  name: Entryway Lights
  entities:
    - light.entryway_flood
    - light.entryway_small

- platform: group
  name: Kitchen Ceiling Lights
  entities:
    - light.kitchen_center
    - light.kitchen_ne
    - light.kitchen_nw
    - light.kitchen_se
    - light.kitchen_sw

- platform: group
  name: Hallway Lights
  entities:
    - light.hall_north
    - light.hall_south

- platform: group
  name: Basement Hallway Lights
  entities:
    - light.basement_hall_1
    - light.basement_hall_2

- platform: group
  name: Living Room Ceiling
  entities:
    - light.lr_ceiling_1
    - light.lr_ceiling_2
    - light.lr_ceiling_3
    - light.lr_ceiling_4
    - light.lr_ceiling_5
