version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: cy-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    restart: unless-stopped

  pi-hole:
    image: pihole/pihole:latest
    container_name: cy-pihole
    environment:
      - TZ=America/Chicago
      - WEBPASSWORD=
    volumes:
      - ./pihole/etc-pihole:/etc/pihole
      - ./pihole/etc-dnsmasq.d:/etc/dnsmasq.d
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8080:80"
    restart: unless-stopped

  watchtower:
    image: containrrr/watchtower
    container_name: cy-watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: cy-ha
    ports:
      - "8123:8123"
    volumes:
      - ./homeassistant:/config
    restart: unless-stopped
    networks:
      - cynet
    privileged: true
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: cy-mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    restart: unless-stopped
    networks:
      - cynet
  zigbee2mqtt:
    image: koenkk/zigbee2mqtt
    container_name: cy-z2m-new
    depends_on:
      - mosquitto
    ports:
      - "8081:8080"
    volumes:
      - ./zigbee2mqtt:/app/data
    restart: unless-stopped
    networks:
      - cynet
networks:
  cynet:
    driver: bridge
