services:
  glances:
    image: nicolargo/glances:latest-full
    container_name: glances
    restart: unless-stopped
    ports:
      - "61209:61209"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    pid: host
    command: glances --enable-plugin restful --server -p 61209
    networks:
      - compose_cynet

networks:
  compose_cynet:
    external: true
