services:
  glances:
    image: nicolargo/glances:latest-alpine
    container_name: glances
    restart: unless-stopped
    ports:
      - "61208:61208"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    pid: host
    command: glances --enable-plugin restful --server
    networks:
      - compose_cynet

networks:
  compose_cynet:
    external: true
