version: "3.9"

services:
  mosquitto:
    dns:
      - 192.168.1.177
      - 1.1.1.1
    image: eclipse-mosquitto:latest
    container_name: cy-mosquitto-z2m
    ports:
      - "1883:1883"
    volumes:
      - /home/andy/buzzgate/compose/mosquitto/config:/cy-config
      - /home/andy/buzzgate/compose/mosquitto/data:/mosquitto/data
      - /home/andy/buzzgate/compose/log:/mosquitto/log
    command: mosquitto -c /cy-config/default.conf
    restart: unless-stopped
    networks:
      - compose_cynet

    healthcheck:
      test: ["CMD", "mosquitto_sub", "-h", "localhost", "-t", "$SYS/broker/version", "-C", "1"]
      interval: 10s
      timeout: 5s
      retries: 5

  z2m-lite:
    image: koenkk/zigbee2mqtt
    container_name: z2m-lite
    restart: unless-stopped

    depends_on:
      mosquitto:
        condition: service_healthy

    ports:
      - "4242:4242"
    dns:
      - 192.168.1.177
      - 1.1.1.1
    volumes:
      - /home/andy/buzzgate/compose/zigbee2mqtt:/app/data
    devices:
      - /dev/serial/by-id/usb-SMLIGHT_SMLIGHT_SLZB-07_eccaf5a21f72ef11b8da3b848fcc3fa0-if00-port0:/dev/ttyUSB0
    privileged: true
    networks:
      - compose_cynet

    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8080"]
      interval: 20s
      timeout: 5s
      retries: 5

networks:
  compose_cynet:
    external: true
