version: '3.8'

services:
  jellyfin:
    image: jellyfin/jellyfin:10.11.6
    container_name: jellyfin
    ports:
      - "8096:8096"  # HTTP access
      # - "8920:8920"  # Uncomment for HTTPS if using reverse proxy
    volumes:
      # Primary media (Synology)
      - /volume1/media1/movies:/media/movies
      - /volume1/media1/extras:/media/extras

      # Secondary SSD media
      - /mnt/jellyfin/media2:/media/media2

      # Jellyfin config + cache (Synology)
      - /volume1/JellyfinConfig:/config
      - /volume1/JellyfinCache:/cache

    environment:
      - TZ=America/Chicago
      - PUID=1026
      - PGID=100
    restart: unless-stopped

