version: '3.8'

services:
  jellyfin:
    image: jellyfin/jellyfin:10.11.6
    container_name: jellyfin
    ports:
      - "8096:8096"  # HTTP access
      # - "8920:8920"  # Uncomment for HTTPS if using reverse proxy
    volumes:
      # NAS movie library
      - /mnt/nas_media/movies:/media/nas_movies

      # PHIXERO SSD movie library
      - /mnt/phixero/Movies:/media/ssd_movies
      # PHIXERO SSD TV library
      - /mnt/phixero/TV:/media/ssd_tv
      # PHIXERO SSD book library
      - /mnt/phixero/Books:/media/ssd_books
      # PHIXERO SSD Documentaries library
      - /mnt/phixero/Documentaries and Instructional Videos:/media/ssd_documentaries

      # Jellyfin config + cache (Synology)
      - /volume1/JellyfinConfig:/config
      - /volume1/JellyfinCache:/cache
      
      - /mnt/music:/media/music

    environment:
      - TZ=America/Chicago
      - PUID=1026
      - PGID=100
    restart: unless-stopped

