version: '3.8'

services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    ports:
      - "8096:8096"  # HTTP access
      # - "8920:8920"  # Uncomment for HTTPS if using reverse proxy
    volumes:
      - /volume1/JellyfinConfig:/config
      - /volume1/JellyfinCache:/cache
      #- /home/admin1/testmovies:/media/movies
      - /mnt/jellyfin/movies:/media/movies
      - /mnt/jellyfin/media2:/media/media2
      - /volume1/JellyfinVault/extras:/media/extras
    environment:
      - TZ=America/Chicago
      - PUID=1026  # Replace with your admin UID
      - PGID=100  # Replace with your media group GID
    restart: unless-stopped
