version: "3.8"

services:
  nocodb:
    image: nocodb/nocodb:0.202.8
    container_name: nocodb
    ports:
      - "8090:8080"
    environment:
      NC_DB: "sqlite"
      NC_PUBLIC_URL: "http://cy:8090"
      NC_AUTH_JWT_SECRET: "HpBM5oG9RsMSdVeS"
    volumes:
      - /home/andy/buzzgate/compose/nocodb/nc_data:/usr/app/data
    restart: unless-stopped
#     networks:
#       - compose_cynet

# networks:
#   compose_cynet:
#     external: true
