groups:
  - name: container-alerts
    rules:
      - alert: ContainerDown
        expr: time() - container_last_seen > 60
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Container '{{ $labels.name }}' may be down"
          description: "No recent activity from container '{{ $labels.name }}'."
