global:
  scrape_interval: 15s
rule_files:
  - "alert.rules.yml"
  - "buzzgate.rules.yml"

scrape_configs:
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
  - job_name: 'alertmanager'
    static_configs:
      - targets: ['alertmanager:9093']
