- platform: rest
  name: directus_tasks_andy
  resource: !secret directus_url_andy
  method: GET
  headers:
    Authorization: !secret directus_token
  value_template: "{{ value_json.data | length }}"
  json_attributes_path: "$.data"
  json_attributes:
    - id
    - title
    - description
    - Frequency
    - done
    - assigned_to
  scan_interval: 30
