- platform: rest
  name: directus_tasks_kia
  resource: !secret directus_url_kia
  method: GET
  headers:
    Authorization: !secret directus_token
  value_template: "{{ value_json.data | length }}"
  json_attributes:
    - data

