- platform: rest
    name: Brain CPU Usage
    resource: http://cy:61208/glances/api/3/cpu
    value_template: "{{ value_json.percent }}"
    scan_interval: 30
    
  # - platform: mqtt
  #   name: "Kiasbutton Action"
  #   state_topic: "zigbee2mqtt/0xcc86ecfffec3c653"
  #   value_template: "{{ value_json.action }}"
    
  - platform: rest
    name: Brain RAM Usage
    resource: http://cy:61208/glances/api/3/mem
    value_template: "{{ value_json.percent }}"
    scan_interval: 30

  - platform: rest
    name: Brain Disk Usage
    resource: http://cy:61208/glances/api/3/fs
    value_template: "{{ value_json[0].percent }}"
    scan_interval: 60
