global:
  resolve_timeout: 5m

route:
  receiver: 'sms-uscellular'
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 30s
  repeat_interval: 1h

receivers:
  - name: 'default'
  - name: sms-uscellular
    email_configs:
      - to: '5152099351@email.uscc.net'
        from: 'ndyjrdn@gmail.com'
        smarthost: 'smtp.gmail.com:587'
        auth_username: 'ndyjrdn'
        auth_password: 'rqsr slnv mamg jiia'
        require_tls: true
